### ISSUE TITLE
Test authn-k8s on Conjur-OSS deployed via Helm chart on OpenShift

### ISSUE THREAD

**Issue by diverdane** [conjurdemos/kubernetes-conjur-demo#110]
## Is your feature request related to a problem? Please describe.

Helm chart deployment of Conjur-OSS on OpenShift should be tested.
This should include deployment of applications that use authn-k8s authentication, and this
can be done using these kubernetes-conjur-demo scripts.

This should include any necessary changes:
- To the demo scripts or related README/CHANGLOG documentation.
- Conjur OSS helm chart

## Describe the solution you would like

- Conjur OSS cluster is deployed via Helm chart to OpenShift.
- Applications using authn-k8s are tested on this Conjur OSS cluster using both host-ID-based and
   annotation-based identity.

**Comment by diverdane** [comment]
Blocked by:
- conjur #1853: There are RH-friendly images for deploying Conjur to OpenShift

**Comment by diverdane** [comment]
I believe that we're now unblocked, as Guy has provided RH-friendly images for both Conjur and NGINX.

**Comment by izgeri** [comment]
This is currently waiting for a new Conjur release (should happen in the next few days, and should publish a new image to the [RH container registry](https://connect.redhat.com/project/5899501/images))

And a resolution to cyberark/conjur-base-image#42 to publish the [Nginx image](https://connect.redhat.com/project/5899451/images) to RH container registry

**Comment by izgeri** [comment]
This ticket is still blocked while we wait for persistent volume support in our OCP cluster. It appears that will be available in OCP 4.6, and we'll also use these automated tests to validate support of OSS on OCP 4.6 once this card is completed.

**Comment by izgeri** [comment]
I propose that we finish #128 before starting this card
