### ISSUE TITLE
MINIKUBE variable is unbound

### ISSUE THREAD

**Issue by infamousjoeg** [conjurdemos/kubernetes-conjur-demo#19]
https://github.com/conjurdemos/kubernetes-conjur-demo/blob/f11ea131ef330a2349b0d6bce4b2500d6899e22d/5_build_and_push_containers.sh#L18

Suggest adding to the `$PLATFORM` check a few lines above:

`MINIKUBE=false` if `$PLATFORM == 'openshift'`

**Comment by izgeri** [comment]
@infamousjoeg we addressed this by creating a script to set the env vars before running: https://github.com/conjurdemos/kubernetes-conjur-demo/blob/master/set_env_vars.sh#L9

In light of this, I'm closing this issue now.
