### ISSUE TITLE
Remove echo'ing DB_PASSWORD - deploy Oracle's Pet Store app instead

### ISSUE THREAD

**Issue by infamousjoeg** [conjurdemos/kubernetes-conjur-demo#35]
Can the `/webapp` and `/test-summon-webapp` deploy the Pet Store demo app instead of just echo'ing back the `$DB_PASSWORD` value.

Our customers like to see something relevant happening and echo'ing back a secret would never occur in any of their environments.

Thanks! ❤️

**Comment by izgeri** [comment]
YES @infamousjoeg !! I too was very much pro this change - all flows in this repo now use the pet store demo app.
