### ISSUE TITLE
kubectl should be $cli for an agnostic approach

### ISSUE THREAD

**Issue by infamousjoeg** [conjurdemos/kubernetes-conjur-demo#4]
https://github.com/conjurdemos/kubernetes-conjur-demo/blob/11baa757d914f7dc9c5c4de64a45545c0852f341/stop#L9

**Comment by izgeri** [comment]
@infamousjoeg - this has been implemented. [see here](https://github.com/conjurdemos/kubernetes-conjur-demo/blob/master/stop#L13)
