### ISSUE TITLE
kubernetes-conjur-demo builds on master are failing

### ISSUE THREAD

**Issue by diverdane** [conjurdemos/kubernetes-conjur-demo#98]
## Summary
The Jenkins builds for the conjurdemos/kubernetes-conjur-demo master branch have been mostly
failing for the last month:

[kubernetes-conjur-demo master builds](https://jenkins.conjur.net/blue/organizations/jenkins/conjurdemos--kubernetes-conjur-demo/activity?branch=master)

There are some occasional passing tests. For the failing test runs, there is some variability: the platform where the errors are showing up seems to vary from test run to test run.

## Steps to Reproduce
Look at the failures in the [kubernetes-conjur-demo master builds](https://jenkins.conjur.net/blue/organizations/jenkins/conjurdemos--kubernetes-conjur-demo/activity?branch=master)

## Expected Results
Jenkins builds should pass consistently.

**Comment by izgeri** [comment]
Since PR https://github.com/conjurdemos/kubernetes-conjur-demo/pull/96 was merged to update the kubectl version, this appears to have stabilized. Closing this issue for now.
